import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/hooks/query-provider";


const inter = localFont({
  src: "./Inter-Variable.ttf",
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Clever Slides: An AI based presentation generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${inter.variable} ${inter.className} antialiased bg-background text-foreground bg-radial from-orange-200 `}>
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
