import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/ui/hooks/query-provider";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Clever Slides: An AI based presentation generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${rubik.variable} ${rubik.className} antialiased`}>
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
