"use client";

import { TextAreaWithButton } from "@/components/ui/textarea-with-button";
import { useRef } from "react";
import { useRouter } from "next/navigation";
import { useDraftStore } from "@/stores/draft-store";
interface PromptProps {
  userId?: string;
}

export default function Prompt({ userId }: PromptProps) {
  const promptRef = useRef<HTMLTextAreaElement>(null);
  const router = useRouter();
  const setDraft = useDraftStore((s) => s.setDraft);

  const onClick = () => {
    if (!promptRef.current) return;
    // No generation for un authenticated users
    const draftId = crypto.randomUUID();

    if (!userId) {
      // Save the prompt and redirect to sign in page
      router.push("/auth/signin");
      return;
    }

    if(!promptRef.current.value) {
      // TODO: Improve with better UI feedback
      alert("Please enter a prompt");
      return;
    }

    // Save draft locally
    setDraft({
      id: draftId,
      prompt: promptRef.current.value,
      content: null, // Later to be generated by AI
      created_at: new Date().toISOString(),
      updated_at: null,
      is_deleted: false,
      status: "draft",
      created_by: userId,
      theme: null,
    });

    // Redirect to regenerate
    router.push("/editor/" + draftId);
  };

  return (
    <TextAreaWithButton
      ref={promptRef}
      onClick={onClick}
      placeholder="Create a professional presentation for a pitch deck about an AI startup"
    />
  );
}
