"use client";

import { Button } from "./button";
import { Textarea } from "./textarea";
import { cn } from "@/lib/utils/tailwind";
import { PaperPlaneTiltIcon } from "@phosphor-icons/react";
import { Input } from "./input";
import { PromptSchema } from "@/lib/schema";
import { usePromptFormStore } from "@/stores/prompt-store";
import { useRouter } from "next/navigation";
import { useDraftStore } from "@/stores/draft-store";
import { Field } from "@/components/ui/field";

interface GenerateInputProps {
  userId?: string;
}

export function GenerateInput({ userId }: GenerateInputProps) {
  const router = useRouter();

  const formState = usePromptFormStore((state) => state.formState);
  const setField = usePromptFormStore((state) => state.setField);
  const errors = usePromptFormStore((state) => state.errors);
  const setError = usePromptFormStore((state) => state.setError);

  const setDraft = useDraftStore((s) => s.setDraft);

  return (
    <form
      className={cn(
        "flex flex-col gap-5 border-primary min-w-3xl placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 field-sizing-content min-h-16 w-full rounded-md border bg-transparent px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50",
      )}
      onSubmit={(e) => {
        e.preventDefault();

        const parsed = PromptSchema.safeParse({
          prompt: formState.prompt,
          width: formState.width,
          height: formState.height,
        });

        if (!parsed.success) {
          console.log(formState);
          console.error("Presentation couldn't generate due to invalid fields");
          return;
        }

        // No generation for un authenticated users
        const draftId = crypto.randomUUID();

        if (!userId) {
          // Save the prompt and redirect to sign in page
          router.push("/auth/signin");
          return;
        }

        // Save draft locally
        setDraft({
          id: draftId,
          prompt: parsed.data.prompt,
          document: null, // Later to be generated by AI
          response: null,
          created_at: new Date().toISOString(),
          updated_at: null,
          is_deleted: false,
          status: "draft",
          created_by: userId,
          theme: null,
        });

        // Redirect to regenerate
        router.push("/editor/" + draftId);
      }}
    >
      <Textarea
        rows={5}
        cols={1}
        placeholder="Create a professional presentation for a pitch deck about an AI startup"
        className="min-h-0 shadow-none border-0 focus-visible:border-none resize-none focus-visible:ring-0"
        onChange={(e) => {
          setField("prompt", e.target.value);

          if (e.target.value === "") {
            setError("prompt", "Please provide a prompt");
          } else {
            setError("prompt", null);
          }
        }}
      />
      <div id="toolbar" className="flex flex-row items-center w-full">
        <div
          id="resolution-tool"
          className="flex flex-row items-center gap-2 text-xs"
        >
          <p>Resolution (px)</p>
          <Field className="w-[50%]">
            <Input
              type="text"
              name="width"
              placeholder="Width"
              defaultValue={formState.width.toString()}
              onChange={(e) => {
                const width = Number(e.target.value);
                setField("width", width);

                if (Number.isNaN(width)) {
                  setError("width", "Invalid dimensions");
                } else if (width >= 4000) {
                  setError("width", "Dimention is beyond 4000 pixels");
                } else {
                  setError("width", null);
                }
              }}
              className="lg:text-xs"
            />
          </Field>
          <Field className="w-[50%]">
            <Input
              type="text"
              name="width"
              placeholder="Height"
              defaultValue={formState.height.toString()}
              onChange={(e) => {
                const height = Number(e.target.value);
                setField("height", height);

                if (Number.isNaN(height)) {
                  setError("height", "Invalid dimensions");
                } else if (height >= 4000) {
                  setError("height", "Dimention is beyond 4000 pixels");
                } else {
                  setError("height", null);
                }
              }}
              className="lg:text-xs"
            />
          </Field>
        </div>
        <Button
          type="submit"
          disabled={
            !formState.height || !formState.width || !formState.prompt
              ? true
              : false
          }
          className="ml-auto text-sm"
        >
          <PaperPlaneTiltIcon size={32} /> Generate
        </Button>
      </div>
      {(errors?.height || errors?.width) && (
        <div
          id="errors"
          className="flex flex-row justify-center text-xs bg-primary rounded-xs p-1"
        >
          <p className="text-black font-bold">
            {errors.height || errors.width
              ? "dimensions must be less than 4000x4000"
              : null}
          </p>
        </div>
      )}
    </form>
  );
}
