import { groq } from "@/lib/groq";
import { buildPresentationPrompt } from "@/lib/prompt";

export async function POST(req: Request) {
  // TODO: Implement auth in routes

  const body = await req.json();

  const messages = buildPresentationPrompt({
    prompt: body.prompt,
  });

  let completion;

  try {
    completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages,
      temperature: 0.3,
      stream: false,
    });
  } catch (error: any) {
    console.log('GROQ ERROR ! =>', error);
    if (error?.code === 429) {
      return new Response(null, {
        status: 500,
        statusText: "Groq API limit has reached",
      });
    }

    return new Response(null, {
      status: 500,
      statusText: `Groq API error`,
    });
  }

  const content = completion.choices[0]?.message?.content;

  if (!content) {
    return new Response(null, {
      status: 500,
      statusText: "Error while generating the prompt",
    });
  }

  let parsedJSON;

  try {
    parsedJSON = JSON.parse(content);
  } catch (error) {
    return new Response(null, {
      status: 500,
      statusText: "Invalid JSON generated by the model",
    });
  }

  return new Response(JSON.stringify(parsedJSON), {
    headers: {
      "Content-Type": "application/json",
    },
  });
}
