import { groq } from "@/lib/groq";
import { buildPresentationPrompt } from "@/lib/prompt";

export async function POST(req: Request) {
  // TODO: Implement auth in routes

  const body = await req.json();

  const messages = buildPresentationPrompt({
    topic: body.topic,
    audience: body.audience,
    slides: body.slides,
  });

  const completion = await groq.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages,
    temperature: 0.3,
    stream: false,
  });

  const content = completion.choices[0]?.message?.content;

  if (!content) {
    return new Response(null, {
      status: 500,
      statusText: "Error while generating the prompt",
    });
  }

  let parsedJSON;

  try {
    parsedJSON = JSON.parse(content);
  } catch (error) {
    return new Response(null, {
      status: 500,
      statusText: "Invalid JSON generated by the model",
    });
  }

  return new Response(JSON.stringify(parsedJSON), {
    headers: {
      "Content-Type": "application/json",
    },
  });
}
