import { groq } from "@/lib/groq";
import { buildPresentationPrompt, buildUpdatePrompt } from "@/lib/prompt";
import { GenerateRequest, GenerateUpdateRequest } from "@/lib/schema";

export async function POST(req: Request) {
  // TODO: Implement auth in routes

  const body = await req.json();

  const generateParsed = GenerateRequest.safeParse(body);
  const updateParsed = GenerateUpdateRequest.safeParse(body);

  let messages;

  if (generateParsed.success) {
    messages = buildPresentationPrompt({
      prompt: generateParsed.data.prompt,
    });
  } else if (updateParsed.success) {
    messages = buildUpdatePrompt({
      updatePrompt: updateParsed.data.updatePrompt,
      currentSlide: updateParsed.data.currentSlide,
    });
  } else {
    return new Response(null, {
      status: 400,
      statusText: "Bad request: no or wrong input prompt is provided",
    });
  }

  let completion;

  try {
    completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages,
      temperature: 0.3,
      stream: false,
    });
  } catch (error: any) {
    console.log("GROQ ERROR ! =>", error);
    if (error?.code === 429) {
      return new Response(null, {
        status: 500,
        statusText: "Groq API limit has reached",
      });
    }

    return new Response(null, {
      status: 500,
      statusText: `Groq API error`,
    });
  }

  const content = completion.choices[0]?.message?.content;

  if (!content) {
    return new Response(null, {
      status: 500,
      statusText: "Error while generating the prompt",
    });
  }

  let parsedJSON;

  console.log(content);

  try {
    parsedJSON = JSON.parse(content);
  } catch (error) {
    return new Response(null, {
      status: 500,
      statusText: "Invalid JSON generated by the model",
    });
  }

  return new Response(JSON.stringify(parsedJSON), {
    headers: {
      "Content-Type": "application/json",
    },
  });
}
